### ISSUE TITLE
Support PHP 7.x

### ISSUE THREAD

**Issue by dany-eudes** [michael-rubel/laravel-formatters#7]
Could you please downgrade to PHP 7.x ?
Maybe PHP 7.4...

Thank you for shared laravel-formatters. This will very very useful for Laravel community.

**Comment by michael-rubel** [comment]
Hi,

Unfortunately, but I'm not going to maintain legacy versions.
Of course, you're free to open PR that adds PHP 7.4 support, but your changes should be compatible with PHP 8.1.

**Comment by dany-eudes** [comment]
Thank you, Michel! I appreciate your awesome work!

**Comment by dany-eudes** [comment]
I checked the compatibility for PHP 7.4 and I came to the conclusion that I would only need to tweak _composer.json_ and comment out the _mixed_ pseudo-type, which is a new feature of PHP 8.

That way, only one of the tests will fail and that's even before the code throws the expected error exception.

I don't know if you would change your mind and you would support PHP 7.4 as well, if so this could be the starting point.

Best Regards.

**Comment by michael-rubel** [comment]
You can open a pull request so we can see if something fails.

**Comment by michael-rubel** [comment]
@dany-eudes You can open a pull request so we can see if something fails.

**Comment by michael-rubel** [comment]
@dany-eudes 
You can open a pull request so we can see if something fails.
